# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/dds_compiler_0/dds_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# IP: ip/cmpy_0/cmpy_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmpy_0 || ORIG_REF_NAME==cmpy_0} -quiet] -quiet

# IP: ip/cordic_0/cordic_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: ip/dsp_macro_0/dsp_macro_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_0 || ORIG_REF_NAME==dsp_macro_0} -quiet] -quiet

# Block Designs: bd/cfo_correction/cfo_correction.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction || ORIG_REF_NAME==cfo_correction} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_conj_0_0/cfo_correction_conj_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_conj_0_0 || ORIG_REF_NAME==cfo_correction_conj_0_0} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_dds_top_0_0/cfo_correction_dds_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_dds_top_0_0 || ORIG_REF_NAME==cfo_correction_dds_top_0_0} -quiet] -quiet

# IP: ip/dds_compiler_0/dds_compiler_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_mixer_0_0/cfo_correction_mixer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_mixer_0_0 || ORIG_REF_NAME==cfo_correction_mixer_0_0} -quiet] -quiet

# IP: ip/cmpy_0/cmpy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmpy_0 || ORIG_REF_NAME==cmpy_0} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_angle_0_0/cfo_correction_angle_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_angle_0_0 || ORIG_REF_NAME==cfo_correction_angle_0_0} -quiet] -quiet

# IP: ip/cordic_0/cordic_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_axis_data_fifo_0_0/cfo_correction_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_axis_data_fifo_0_0 || ORIG_REF_NAME==cfo_correction_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_axis_data_fifo_1_0/cfo_correction_axis_data_fifo_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_axis_data_fifo_1_0 || ORIG_REF_NAME==cfo_correction_axis_data_fifo_1_0} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_axis_splitter_0_0/cfo_correction_axis_splitter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_axis_splitter_0_0 || ORIG_REF_NAME==cfo_correction_axis_splitter_0_0} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_axis_splitter_1_0/cfo_correction_axis_splitter_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_axis_splitter_1_0 || ORIG_REF_NAME==cfo_correction_axis_splitter_1_0} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_complex_mult_0_0/cfo_correction_complex_mult_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_complex_mult_0_0 || ORIG_REF_NAME==cfo_correction_complex_mult_0_0} -quiet] -quiet

# IP: ip/cmpy_0/cmpy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmpy_0 || ORIG_REF_NAME==cmpy_0} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_conj_0_1/cfo_correction_conj_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_conj_0_1 || ORIG_REF_NAME==cfo_correction_conj_0_1} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_conj_1_0/cfo_correction_conj_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_conj_1_0 || ORIG_REF_NAME==cfo_correction_conj_1_0} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_cp_rm2_0_0/cfo_correction_cp_rm2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_cp_rm2_0_0 || ORIG_REF_NAME==cfo_correction_cp_rm2_0_0} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_delay_0_0/cfo_correction_delay_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_delay_0_0 || ORIG_REF_NAME==cfo_correction_delay_0_0} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_delay_1_0/cfo_correction_delay_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_delay_1_0 || ORIG_REF_NAME==cfo_correction_delay_1_0} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_mux_0_0/cfo_correction_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_mux_0_0 || ORIG_REF_NAME==cfo_correction_mux_0_0} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_scale_0_0/cfo_correction_scale_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_scale_0_0 || ORIG_REF_NAME==cfo_correction_scale_0_0} -quiet] -quiet

# IP: ip/dsp_macro_0/dsp_macro_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_0 || ORIG_REF_NAME==dsp_macro_0} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_sum_0_0/cfo_correction_sum_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_sum_0_0 || ORIG_REF_NAME==cfo_correction_sum_0_0} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_util_vector_logic_0_0/cfo_correction_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_util_vector_logic_0_0 || ORIG_REF_NAME==cfo_correction_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_xlconstant_0_0/cfo_correction_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_xlconstant_0_0 || ORIG_REF_NAME==cfo_correction_xlconstant_0_0} -quiet] -quiet

# IP: bd/cfo_correction/ip/cfo_correction_cp_rm_0_0/cfo_correction_cp_rm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfo_correction_cp_rm_0_0 || ORIG_REF_NAME==cfo_correction_cp_rm_0_0} -quiet] -quiet

# XDC: c:/Projects/pi-radio/HW/sims/cfo_correction/cfo_correction.gen/sources_1/bd/cfo_correction/cfo_correction_ooc.xdc
