# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Projects/pi-radio/HW/sims/cfo_correction_board/cfo_correction_board.srcs/sources_1/bd/rx_test/ip/rx_test_xbar_3/rx_test_xbar_3.xci
# IP: The module: 'rx_test_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/pi-radio/HW/sims/cfo_correction_board/cfo_correction_board.gen/sources_1/bd/rx_test/ip/rx_test_xbar_3/rx_test_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rx_test_xbar_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Projects/pi-radio/HW/sims/cfo_correction_board/cfo_correction_board.srcs/sources_1/bd/rx_test/ip/rx_test_xbar_3/rx_test_xbar_3.xci
# IP: The module: 'rx_test_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/pi-radio/HW/sims/cfo_correction_board/cfo_correction_board.gen/sources_1/bd/rx_test/ip/rx_test_xbar_3/rx_test_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rx_test_xbar_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
