# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Projects/pi-radio/HW/sims/cfo_correction/cfo_correction.srcs/sources_1/bd/cfo_correction/ip/cfo_correction_axis_data_fifo_0_0/cfo_correction_axis_data_fifo_0_0.xci
# IP: The module: 'cfo_correction_axis_data_fifo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/pi-radio/HW/sims/cfo_correction/cfo_correction.gen/sources_1/bd/cfo_correction/ip/cfo_correction_axis_data_fifo_0_0/cfo_correction_axis_data_fifo_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cfo_correction_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Projects/pi-radio/HW/sims/cfo_correction/cfo_correction.srcs/sources_1/bd/cfo_correction/ip/cfo_correction_axis_data_fifo_0_0/cfo_correction_axis_data_fifo_0_0.xci
# IP: The module: 'cfo_correction_axis_data_fifo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/pi-radio/HW/sims/cfo_correction/cfo_correction.gen/sources_1/bd/cfo_correction/ip/cfo_correction_axis_data_fifo_0_0/cfo_correction_axis_data_fifo_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cfo_correction_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
