# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_conj_0_0/design_1_conj_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_conj_0_0 || ORIG_REF_NAME==design_1_conj_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cp_rm_0_0/design_1_cp_rm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cp_rm_0_0 || ORIG_REF_NAME==design_1_cp_rm_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_0 || ORIG_REF_NAME==design_1_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_delay_0_0/design_1_delay_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_delay_0_0 || ORIG_REF_NAME==design_1_delay_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_complex_mult_sum_0_0/design_1_complex_mult_sum_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_complex_mult_sum_0_0 || ORIG_REF_NAME==design_1_complex_mult_sum_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_splitter_0_0/design_1_axis_splitter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_splitter_0_0 || ORIG_REF_NAME==design_1_axis_splitter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cp_rm2_0_0/design_1_cp_rm2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cp_rm2_0_0 || ORIG_REF_NAME==design_1_cp_rm2_0_0} -quiet] -quiet

# XDC: c:/Projects/pi-radio/HW/Equalizer_design/Equalizer_design.gen/sources_1/bd/design_1/design_1_ooc.xdc
