# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/rx_test/rx_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_test || ORIG_REF_NAME==rx_test} -quiet] -quiet

# IP: bd/rx_test/ip/rx_test_axi_gpio_0_1/rx_test_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_test_axi_gpio_0_1 || ORIG_REF_NAME==rx_test_axi_gpio_0_1} -quiet] -quiet

# IP: bd/rx_test/ip/rx_test_axi_interconnect_0_1/rx_test_axi_interconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_test_axi_interconnect_0_1 || ORIG_REF_NAME==rx_test_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/rx_test/ip/rx_test_axis_data_fifo_1_1/rx_test_axis_data_fifo_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_test_axis_data_fifo_1_1 || ORIG_REF_NAME==rx_test_axis_data_fifo_1_1} -quiet] -quiet

# IP: bd/rx_test/ip/rx_test_proc_sys_reset_1_1/rx_test_proc_sys_reset_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_test_proc_sys_reset_1_1 || ORIG_REF_NAME==rx_test_proc_sys_reset_1_1} -quiet] -quiet

# IP: bd/rx_test/ip/rx_test_xbar_3/rx_test_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_test_xbar_3 || ORIG_REF_NAME==rx_test_xbar_3} -quiet] -quiet

# IP: bd/rx_test/ip/rx_test_ps8_0_axi_periph_1/rx_test_ps8_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_test_ps8_0_axi_periph_1 || ORIG_REF_NAME==rx_test_ps8_0_axi_periph_1} -quiet] -quiet

# IP: bd/rx_test/ip/rx_test_system_ila_2_1/rx_test_system_ila_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_test_system_ila_2_1 || ORIG_REF_NAME==rx_test_system_ila_2_1} -quiet] -quiet

# IP: bd/rx_test/ip/rx_test_tlast_gen_0_1/rx_test_tlast_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_test_tlast_gen_0_1 || ORIG_REF_NAME==rx_test_tlast_gen_0_1} -quiet] -quiet

# IP: bd/rx_test/ip/rx_test_zynq_ultra_ps_e_0_1/rx_test_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_test_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==rx_test_zynq_ultra_ps_e_0_1} -quiet] -quiet

# IP: bd/rx_test/ip/rx_test_axi_dma_0_1/rx_test_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_test_axi_dma_0_1 || ORIG_REF_NAME==rx_test_axi_dma_0_1} -quiet] -quiet

# IP: bd/rx_test/ip/rx_test_axi_gpio_1_0/rx_test_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_test_axi_gpio_1_0 || ORIG_REF_NAME==rx_test_axi_gpio_1_0} -quiet] -quiet

# IP: bd/rx_test/ip/rx_test_playback_bram_0_0/rx_test_playback_bram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_test_playback_bram_0_0 || ORIG_REF_NAME==rx_test_playback_bram_0_0} -quiet] -quiet

# IP: bd/rx_test/ip/rx_test_blk_mem_gen_0_0/rx_test_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_test_blk_mem_gen_0_0 || ORIG_REF_NAME==rx_test_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/rx_test/ip/rx_test_auto_pc_0/rx_test_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rx_test_auto_pc_0 || ORIG_REF_NAME==rx_test_auto_pc_0} -quiet] -quiet

# IP: ip/cmpy_0/cmpy_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmpy_0 || ORIG_REF_NAME==cmpy_0} -quiet] -quiet

# IP: ip/dds_compiler_0/dds_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# IP: ip/cordic_0/cordic_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: ip/dsp_macro_0/dsp_macro_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_0 || ORIG_REF_NAME==dsp_macro_0} -quiet] -quiet

# XDC: c:/Projects/pi-radio/HW/sims/cfo_correction_board/cfo_correction_board.gen/sources_1/bd/rx_test/rx_test_ooc.xdc
