# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Projects/pi-radio/HW/sims/cfo_correction_board/cfo_correction_board.gen/sources_1/bd/rx_test/bd/cfo_correction_inst_1/ip/cfo_correction_inst_1_angle_0_0_1/cfo_correction_inst_1_angle_0_0.xci
# IP: The module: 'cfo_correction_inst_1_angle_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Projects/pi-radio/HW/sims/cfo_correction_board/cfo_correction_board.srcs/sources_1/ip/cordic_0/cordic_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# XDC: c:/Projects/pi-radio/HW/sims/cfo_correction_board/cfo_correction_board.gen/sources_1/bd/rx_test/bd/cfo_correction_inst_1/ip/cfo_correction_inst_1_angle_0_0_1/cfo_correction_inst_1_angle_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cfo_correction_inst_1_angle_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Projects/pi-radio/HW/sims/cfo_correction_board/cfo_correction_board.gen/sources_1/bd/rx_test/bd/cfo_correction_inst_1/ip/cfo_correction_inst_1_angle_0_0_1/cfo_correction_inst_1_angle_0_0.xci
# IP: The module: 'cfo_correction_inst_1_angle_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Projects/pi-radio/HW/sims/cfo_correction_board/cfo_correction_board.srcs/sources_1/ip/cordic_0/cordic_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# XDC: c:/Projects/pi-radio/HW/sims/cfo_correction_board/cfo_correction_board.gen/sources_1/bd/rx_test/bd/cfo_correction_inst_1/ip/cfo_correction_inst_1_angle_0_0_1/cfo_correction_inst_1_angle_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cfo_correction_inst_1_angle_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
